# Generated by Django 5.2 on 2025-05-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
